### ISSUE TITLE
QP handle arbitrary experiment number/reference number

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#1118]
Issue raised by: developer

### What?
It seems the validation of the experiment number can be things that aren't even integers, such as in this case: `CAL_MARI_11/12/2020 12:20:24`. However the QP assumes they will always be ints, so it just does `experiment = db_access.get_experiment(message.rb_number)`, which fails with ValueError as the DB field does not expect a string.

I am not 100% sure what is the best course of action - the experiment cannot be blank in the `ReductionRun` model, so we can't just make a ReductionRun object and mark it as skipped.

Might be best to inspect the old QP code and see if it handled this case, and how.

<details>
<summary>Traceback</summary>

[11/Feb/2021 14:04:04] ERROR [queue_listener:84] Unhandled exception encountered: ValueError Field 'reference_number' expected a number but got 'CAL_MARI_11/12/2020 12:20:24'.

Traceback (most recent call last):
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'CAL_MARI_11/12/2020 12:20:24'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "queue_processors/queue_processor/queue_listener.py", line 79, in on_message
    self.message_handler.data_ready(message)
  File "/home/dtasev/dev/autoreduce/queue_processors/queue_processor/handle_message.py", line 60, in data_ready
    reduction_run, message, instrument = self.create_run_records(message)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/dtasev/dev/autoreduce/queue_processors/queue_processor/handle_message.py", line 87, in create_run_records
    experiment = db_access.get_experiment(message.rb_number)
  File "/home/dtasev/dev/autoreduce/model/database/access.py", line 56, in get_experiment
    return database.data_model.Experiment.objects.get_or_create(reference_number=rb_number)[0]
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1380, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/dtasev/apps/miniconda3/envs/ar/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1778, in get_prep_value
    ) from e
ValueError: Field 'reference_number' expected a number but got 'CAL_MARI_11/12/2020 12:20:24'.

</details>

### How?
Run `python scripts/manual_operations/manual_submission.py MARI 27878`

### Reproducible?
Yes

### How to test the issue is resolved
Not sure what the best resolution is

**Comment by keiranjprice101** [comment]
I have a feeling for calibration runs the RB number was set to 0 to handle this case, which may also be related to #855

**Comment by dtasev** [comment]
I wonder if there's a point getting the experiment object for *any* run that does not fall in `999999 < rb_number < 10000000`, should we just assign RB 0 to them? @Anders-Markvardsen
