### ISSUE TITLE
Fix the django webapp tests

### ISSUE THREAD

**Issue by ElliotAOram** [ISISScientificComputing/autoreduce#18]
Currently there are 15 failing tests in the Django web app (see test output below) these should all be fixed and added to CI after #17 is complete

Tests should also be cleaned up as part of this issue

 ```
.E......F..FEEEEEE......................................................EEEEE..E
======================================================================
ERROR: test_get_current_and_upcoming_variables_test_upcoming (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 139, in test_get_current_and_upcoming_variables_test_upcoming
    upcoming = InstrumentVariablesUtils().set_default_instrument_variables(testInstrument, 99999)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'set_default_instrument_variables'

======================================================================
ERROR: test_get_variables_for_run_default_variables (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 237, in test_get_variables_for_run_default_variables
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_get_variables_for_run_experiment_reference (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 201, in test_get_variables_for_run_experiment_reference
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_get_variables_for_run_run_number (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 223, in test_get_variables_for_run_run_number
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_set_default_instrument_variables_empty (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 124, in test_set_default_instrument_variables_empty
    variables = InstrumentVariablesUtils().set_default_instrument_variables("empty_script", 1)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'set_default_instrument_variables'

======================================================================
ERROR: test_set_default_instrument_variables_no_start_run (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 116, in test_set_default_instrument_variables_no_start_run
    variables = InstrumentVariablesUtils().set_default_instrument_variables("valid", None)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'set_default_instrument_variables'

======================================================================
ERROR: test_set_default_instrument_variables_successful (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 104, in test_set_default_instrument_variables_successful
    variables = InstrumentVariablesUtils().set_default_instrument_variables("valid", 1)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'set_default_instrument_variables'

======================================================================
ERROR: test_cancel_not_queued (test.test_reduction_viewer.ReductionRunUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 132, in test_cancel_not_queued
    reductionRun = self.createReductionRun()
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 85, in createReductionRun
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_cancel_queued (test.test_reduction_viewer.ReductionRunUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 102, in test_cancel_queued
    reductionRun = self.createReductionRun()
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 85, in createReductionRun
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_cancel_rerun_queued (test.test_reduction_viewer.ReductionRunUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 111, in test_cancel_rerun_queued
    reductionRun = self.createReductionRun()
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 85, in createReductionRun
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_createRetryRun (test.test_reduction_viewer.ReductionRunUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 142, in test_createRetryRun
    reductionRun = self.createReductionRun()
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 85, in createReductionRun
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test_createRetryRun_duplicate (test.test_reduction_viewer.ReductionRunUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 162, in test_createRetryRun_duplicate
    reductionRun = self.createReductionRun()
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_viewer.py", line 85, in createReductionRun
    variables = InstrumentVariablesUtils().get_variables_for_run(reduction_run)
AttributeError: 'InstrumentVariablesUtils' object has no attribute 'get_variables_for_run'

======================================================================
ERROR: test.test_autoreduce_webapp (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_autoreduce_webapp
Traceback (most recent call last):
  File "C:\Python27\Lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\Lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_autoreduce_webapp.py", line 24, in <module>
    from autoreduce_webapp.queue_processor_daemon import QueueProcessorDaemon
ImportError: No module named queue_processor_daemon


======================================================================
FAIL: test_get_default_variables_missing (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 76, in test_get_default_variables_missing
    self.assertTrue(len(updated_notification) > len(initial_notification), 'Expecting a notification to be created')
AssertionError: Expecting a notification to be created

======================================================================
FAIL: test_get_default_variables_syntax_error (test.test_reduction_variables.InstrumentVariablesUtilsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hvq65228\Documents\git\autoreduce\WebApp\autoreduce_webapp\test\test_reduction_variables.py", line 67, in test_get_default_variables_syntax_error
    self.assertTrue(len(updated_notification) > len(initial_notification), 'Expecting a notification to be created')
AssertionError: Expecting a notification to be created

----------------------------------------------------------------------
Ran 80 tests in 4.294s

FAILED (failures=2, errors=13)
```

**Comment by ElliotAOram** [comment]
See issue #121
