### ISSUE TITLE
`/` no longer redirects to `/overview`

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#882]
Issue raised by: dev

### What?
Home `/` used to redirect the user to `/overview`, now it seems to be showing a 500 server error

### Where?
Go to root URL `/` of the web app

### How?
How did the issue come about

### Reproducible?
[Yes/No]

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by rickybassom** [comment]
As oberserved on the production server:
```2020-11-04 16:14:42,870 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "c:\python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\reduction_viewer\view_utils.py", line 39, in request_processor
    return func(request, *args, **kws)
  File "C:\Autoreduction\WebApp\autoreduce_webapp\reduction_viewer\views.py", line 64, in index
    and UOWSClient().check_session(request.session['sessionId'])
  File "c:\python37\lib\site-packages\django\contrib\sessions\backends\base.py", line 64, in __getitem__
    return self._session[key]
KeyError: 'sessionId'
``

I can't reproduce this locally however.
